postgres: &postgres
  adapter: postgresql
  host: 127.0.0.1
  user: ben
  password: 
  encoding: unicode
  pool: 5

development:
  database: hstore_blog_development
  <<: *postgres

production:
  database: hstore_blog_production
  <<: *postgres

test:
  database: hstore_blog_test
  <<: *postgres
